# Generated by Django 4.2.30 on 2026-04-16 21:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('riding_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень катания (1-5)')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Медицинские заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Уровень подготовки (1-5)')),
                ('max_workload_per_day', models.PositiveSmallIntegerField(default=3, verbose_name='Макс. занятий в день')),
                ('rest_hours_between', models.PositiveSmallIntegerField(default=2, verbose_name='Часы отдыха между занятиями')),
                ('notes', models.TextField(blank=True, verbose_name='Особые отметки')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Лошадь',
                'verbose_name_plural': 'Лошади',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('duration', models.PositiveSmallIntegerField(help_text='Длительность в минутах', verbose_name='Длительность (мин)')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая стоимость')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('max_horses_per_day', models.PositiveSmallIntegerField(default=4, verbose_name='Макс. лошадей в день')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('visits', models.PositiveSmallIntegerField(verbose_name='Количество занятий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('validity_days', models.PositiveSmallIntegerField(verbose_name='Срок действия (дней)')),
                ('is_active', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('visits_total', models.PositiveSmallIntegerField()),
                ('remaining_visits', models.PositiveSmallIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='booking.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.subscription')),
            ],
            options={
                'verbose_name': 'Абонемент клиента',
                'verbose_name_plural': 'Абонементы клиентов',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('no_show', 'Неявка')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Списанная сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.client', verbose_name='Клиент')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.horse', verbose_name='Лошадь')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.servicetype', verbose_name='Услуга')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.trainer', verbose_name='Тренер')),
                ('used_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.clientsubscription', verbose_name='Использованный абонемент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-start_time'],
            },
        ),
    ]
