# Generated by Django 4.2.30 on 2026-04-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Процент от стоимости услуг (%)'),
        ),
    ]
