# Generated by Django 4.2.30 on 2026-04-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_trainer_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('certificate', 'Подарочный сертификат'), ('subscription', 'Абонемент')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
